#!/bin/bash

status="$(cat /sys/class/power_supply/BAT0/status)"
level="$(cat /sys/class/power_supply/BAT0/capacity)"

if [[ "$status" == "Discharging" || "$status" == "Full" ]]; then
  if (( level == 0 )); then
    echo -n "    $level%"  
  elif (( level > 0 && level <= 25 )); then
    echo -n "    $level%"  
  elif (( level > 25 && level <= 50 )); then
    echo -n "    $level%"  
  elif (( level > 50 && level <= 75 )); then
    echo -n "    $level%"  
  elif (( level > 75 && level <= 100 )); then
    echo -n "    $level%"  
  fi
elif [[ "$status" == "Charging" ]]; then
  echo -n "    $level%"  
else
  echo "Unknown status"
fi
