#!/bin/bash

status=$(nmcli -t -f STATE general)

if [[ "$status" == "disconnected" ]]; then
  echo "   Disconnected"
elif [[ "$status" == "connecting" ]]; then
  echo "   Connecting..."
elif [[ "$status" == "connected" ]]; then
  ssid=$(nmcli -t -f ACTIVE,SSID dev wifi | awk -F: '$1=="yes" {print $2}')
  strength=$(nmcli -t -f SIGNAL dev wifi | awk 'NR==1 {print $1}')

  if [[ -z "$ssid" ]]; then
    echo "  Unknown Network"
  else
    if [[ "$strength" -le 25 ]]; then
      icon=""
    elif [[ "$strength" -le 50 ]]; then
      icon=""
    elif [[ "$strength" -le 75 ]]; then
      icon=""
    else
      icon=""
    fi
    echo "$icon   $ssid"
  fi
fi
